micronaut:
    application:
        name: nxflogger
database:
    name: workflows
    tables:
        runs: WorkflowRuns
        traces: WorkflowTraces
datasources:
        default:
            url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            username: testuser
            password: ""
            driverClassName: org.h2.Driver

