micronaut:
    application:
        name: nxflogger
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
contact:
    first-name: ${wf-contact-first-name}
    last-name: ${wf-contact-last-name}
    email: ${wf-contact-email}
database:
    name: workflows
datasources:
        default:
            url: jdbc:mariadb://${wf-db-host}/${wf-db-name}
            username: ${wf-db-user}
            password: ${wf-db-pwd}
            driverClassName: org.mariadb.jdbc.Driver