micronaut:
    application:
        name: nxflogger
database:
    name: workflows
datasources:
        default:
            url: jdbc:mariadb://$WF_DB_HOST/$WF_DB_NAME
            username: $WF_DB_USER
            password: $WF_DB_PWD
            driverClassName: com.mariadb.jdbc.Driver
