micronaut:
    application:
        name: nxflogger
    server:
        port: ${wf-server-port:8080}
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
contact:
    first-name: ${wf-contact-first-name:Max}
    last-name: ${wf-contact-last-name:Mustermann}
    email: ${wf-contact-email:'max.mustermann@uni-tuebingen.de'}
userroles:
    config: ${domain-userroles:/etc/micronaut.d/userroles.yml}
database:
    name: workflows
datasources:
        default:
            url: jdbc:mariadb://${wf-db-host}/${wf-db-name}?maxPoolSize=${wf-max-pool-size:50}&pool
            username: ${wf-db-user}
            password: ${wf-db-pwd}
            driverClassName: org.mariadb.jdbc.Driver
endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
    routes:
        enabled: true
        sensitive: false