micronaut:
    application:
        name: nxflogger
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
contact:
    first-name: ${wf-contact-first-name:Max}
    last-name: ${wf-contact-last-name:Mustermann}
    email: ${wf-contact-email:'max.mustermann@uni-tuebingen.de'}
database:
    name: workflows
datasources:
        default:
            url: jdbc:mariadb://${wf-db-host}/${wf-db-name}?maxPoolSize=150&pool
            username: ${wf-db-user}
            password: ${wf-db-pwd}
            driverClassName: org.mariadb.jdbc.Driver
endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS