micronaut:
    application:
        name: nxflogger
contact:
    first-name: Hellow
    last-name: Word
    email: hellow.word@example.com
database:
    schema-uri: "src/test/resources/db-setup.sql"
userroles:
    config: "src/test/resources/userroles.yml"
datasources:
        default:
            url: jdbc:h2:${h2-path}/workflows;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            username: testuser
            password: ""
            driverClassName: org.h2.Driver
